### ISSUE TITLE
MemoryAdapter does not have collection defined

### ISSUE THREAD

**Issue by ryanmalesic** [moleculerjs/moleculer-db#226]
this.adapter.collection.* throws because collection is undefined when using the memory adapter. I don't know if this is supposed to be the case, but it inhibits the use of operations like createIndex or distinct during tests and development

**Comment by icebob** [comment]
The `this.adapter.*` depends on your adapter, it's not uniform. 
If you use Mongo adapter, you have `this.adapter.collection`, if you use Mongoose adapter, you have `this.adapter.model`...etc. Memory adapter has no any fields because it handles only one collection. 

If you want to use multiple adapters, you should write different codes for different adapters.
